### PR TITLE
Delete all monticello metadata

### PR DESCRIPTION
**Pull request by tom95**
Preface: Please note that I don't exactly know what I'm doing. I have never used the monticello metadata format and am not sure what repercussions this change may entail.

Problem: The Metacello bootstrap process first loads a rather old Metacello from gemtalk squeaksource. This version appears to create empty `version` in the monticello.meta directory if it exists. However, upon finding an empty `version` file later, it will be unable to parse it.

Workaround: By deleting the monticello.meta folders it appears to no longer hit the problematic code paths with the old version. Loading works with both old and new Metacello. A proper test of `Installer ensureRecentMetacello` can of course not be done until this is merged, but modifying the Ston repo path in the baseline after the error occurred to this fork allowed me to load Ston in a Squeak 5.3.

### CODE REVIEW

**Comment by krono** [comment]
This restricts working on this repo to Squot, right?

**Comment by tom95** [comment]
Not entirely sure, I suppose alternatively we could try generating the missing `version` files?

**Comment by krono** [comment]
maybe this is related? aba7f7a0599ad7fe7f4657dde899cd1ddd51cbbf

**Comment by krono** [comment]
Similarly, 6a894a483ff3c7d963e914c96338660c9ecad278
It seems the tools @svenvc uses remove the version file one by one, whenever there's a commit in the respecitve package. 

If used with squot, no problem, if used with pure filetree, we lose history info. 

But since the state is now inconsistent, removing the remaining motincello sexp files might be an ok thing to do. @j4yk, any opinion?

**Comment by tom95** [comment]
My wild guess right now would be that the Metacello used for bootstrapping does not support partial metadata/metadataless repos and is thus failing to load STON, which is of course problematic since in order to get the new version of Metacello we need to be loadable via the old version. Maybe @dalehenrich would happen to know more?

**Comment by svenvc** [comment]
At one point in time I was looking at the changes you guys were doing to STON for Squeak but I stopped because the diff was massive due to all the meta data changes.

There is a reason we in the Pharo world work differently: merging/diffing/anything with normal scm tools like git becomes a nightmare. Also, in the end Tonel is better than FileTree but I did not make that change to maintain better portability.

Just my 2c

**Comment by krono** [comment]
> At one point in time I was looking at the changes you guys were doing to STON for Squeak but I stopped because the diff was massive due to all the meta data changes.
> 
> There is a reason we in the Pharo world work differently: merging/diffing/anything with normal scm tools like git becomes a nightmare. Also, in the end Tonel is better than FileTree but I did not make that change to maintain better portability.
> 
> Just my 2c

Fair.

So, let's zap the files

**Comment by tom95** [comment]
Some more details after comparing the Metacello on gemsource with the one currently on GitHub:

The gemsource Metacello will only check for existence of the monticello.meta folder and then proceed to access the version file. The GitHub version does so using readOnlyFileNamed, while the gemsource one will use fileNamed, and as such create an empty file if it does not exist, thus failing to parse it right after.

The two alternatives to this PR are as far as I can see are as such this:
1. update the gemsource Metacello to check for existence of the version file as the GitHub Metacello does (`MCFiletreeAbstractReader>>#hasMonticelloMetadata`)
2. generate version files in the squeak-ston repo for each category to make the package compatible with the old loading behavior
3. or use this PR, which essentially just prevents the code path from running that will try to access the version file. As far as I can tell we are also not losing anything, categories are correctly loaded even with the changes in this PR and all version information is currently missing anyway.

**Comment by krono** [comment]
na, its fine, lets use the pr. fabio?

**Comment by dalehenrich** [comment]
I'm not quite sure why the GemSource Metacello code is involved? The GemSource code is used to bootstrap Metacello from older versions of Metacello to newer versions of Metacello (the versions of Metacello that pre-dated BaselineOf and the github repository), so changing the GemSource code is not recommended ... 

Just guessing, but it is better to load Metacello directly from github if possible ...

**Comment by tom95** [comment]
Hey Dale! Since we added STON as a dependency to Metacello on Squeak in the recent PR, the Metacello version used to bootstrap the "real" Metacello now also needs to be able to load STON. Loading STON is however currently not possible with the gemsource version as described above.

Could you elaborate on your last comment about loading Metacello from GitHub directly? Do you mean skipping the current bootstrap process? That would be a very interesting option since it would remove dependencies on code that is hosted on the now deprecated smalltalkhub.

**Comment by dalehenrich** [comment]
>Could you elaborate on your last comment about loading Metacello from GitHub directly? Do you mean skipping the current bootstrap process? That would be a very interesting option since it would remove dependencies on code that is hosted on the now deprecated smalltalkhub.

Yes that is what I am thinking ... if you are able to load FileTree code without having to use Metacello, then it should be possible to install Metacello directly from git-based source ... I'm pretty sure that the convoluted install process for Metacello was necessary to install FileTree support using Metacello ...

**Comment by krono** [comment]
> > Could you elaborate on your last comment about loading Metacello from GitHub directly? Do you mean skipping the current bootstrap process? That would be a very interesting option since it would remove dependencies on code that is hosted on the now deprecated smalltalkhub.
> 
> Yes that is what I am thinking ... if you are able to load FileTree code without having to use Metacello, then it should be possible to install Metacello directly from git-based source ... I'm pretty sure that the convoluted install process for Metacello was necessary to install FileTree support using Metacello ...

That's exactly it…

**Comment by dalehenrich** [comment]
It will be easier if you can install the Metacello prerequisite projects (Filetree and STON(?)) from FileTree or mcz repos without the help of Metacello ... back when Metacello was first introduced, it needed to be bootstrapped from Monticello because it needed to be loaded into images where Metacello didn't exist ... if you are building images with Metacello pre-installed, these shortcuts can be taken:)

**Comment by krono** [comment]
> […]if you are building images with Metacello pre-installed, these shortcuts can be taken:)

No, we don't have those, that's partly the point…

**Comment by dalehenrich** [comment]
One trick I have used in the past, is to export a FileTree project to mcz files and keep the mcz files around for bootstrapping ... it works best if the project you are copying to mcz files is not changing very often:) ... but that could easily be the case with STON and Filetree (definitely Filetree:)

**Comment by krono** [comment]
Good point!

**Review by krono — APPROVED** [review]

**Comment by dalehenrich** [comment]
In retrospect, using mcz bootstrap file might be easier to manage, since once you've bootstrapped Metacello, you can load those two projects using the latest versions on github ... those two projects are less complex than the Metacello upgrade process...

**Comment by fniephaus** [comment]
I'm going to merge this now without having read the conversation above. I've been too busy to follow up on this, but @krono approved it and @tom95 asked me to hit the merge button. We can always revert if this turns out to be a bad idea.

**Pull request merged**
